/*-
 * WSDL stubs for:  http://dblp.l3s.de/WS/dblp++.php?wsdl
 *   Generated by:  matthias
 *           Date:  Fri May  7 14:39:59 2010
 *        Emitter:  Objective-C
 */

#ifndef __DBLP__
#define __DBLP__

#import <CoreServices/CoreServices.h>
#import <Foundation/Foundation.h>
#import "WSGeneratedObj.h"

/*-
 *   Web Service:  DBLPPlusPlusService
 * Documentation:  <not documented>
 */
/*-
 *   Method Name:  venue_title
 * Documentation:  <no documentation>
 */

@interface venue_title : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* venue_title */


/*-
 *   Method Name:  publication_data2
 * Documentation:  <no documentation>
 */

@interface publication_data2 : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* publication_data2 */


/*-
 *   Method Name:  all_publications_keywords_year
 * Documentation:  <no documentation>
 */

@interface all_publications_keywords_year : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_searchTerm in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear in_limit:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_limit;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* all_publications_keywords_year */


/*-
 *   Method Name:  all_publications_venue_year
 * Documentation:  <no documentation>
 */

@interface all_publications_venue_year : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key_frag in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* all_publications_venue_year */


/*-
 *   Method Name:  all_journal_titles
 * Documentation:  <no documentation>
 */

@interface all_journal_titles : WSGeneratedObj

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* all_journal_titles */


/*-
 *   Method Name:  publication_bibtex
 * Documentation:  <no documentation>
 */

@interface publication_bibtex : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* publication_bibtex */


/*-
 *   Method Name:  all_journal_titles_year
 * Documentation:  <no documentation>
 */

@interface all_journal_titles_year : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_year;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* all_journal_titles_year */


/*-
 *   Method Name:  publication_data
 * Documentation:  <no documentation>
 */

@interface publication_data : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* publication_data */


/*-
 *   Method Name:  all_proceeding_titles
 * Documentation:  <no documentation>
 */

@interface all_proceeding_titles : WSGeneratedObj

// No parameters for this method

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* all_proceeding_titles */


/*-
 *   Method Name:  all_publications_author_year
 * Documentation:  <no documentation>
 */

@interface all_publications_author_year : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_firstName in_familyName:(NSString*) in_familyName in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* all_publications_author_year */


/*-
 *   Method Name:  publication_authors
 * Documentation:  <no documentation>
 */

@interface publication_authors : WSGeneratedObj

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_dblp_key;

// result returns an id from the reply dictionary as specified by the WSDL.
- (id) resultValue;

@end; /* publication_authors */


/*-
 * Web Service:  DBLPPlusPlusService
 */
@interface DBLPPlusPlusService : NSObject 

+ (id) all_publications_author_year:(NSString*) in_firstName in_familyName:(NSString*) in_familyName in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear;
+ (id) publication_data2:(NSString*) in_dblp_key;
+ (id) publication_authors:(NSString*) in_dblp_key;
+ (id) all_publications_venue_year:(NSString*) in_dblp_key_frag in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear;
+ (id) all_journal_titles;
+ (id) publication_bibtex:(NSString*) in_dblp_key;
+ (id) all_publications_keywords_year:(NSString*) in_searchTerm in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear in_limit:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_limit;
+ (id) venue_title:(NSString*) in_dblp_key;
+ (id) all_journal_titles_year:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_year;
+ (id) publication_data:(NSString*) in_dblp_key;
+ (id) all_proceeding_titles;

@end;


#endif /* __DBLP__ */
/*-
 * End of WSDL document at http://dblp.l3s.de/WS/dblp++.php?wsdl
 */
