/*-
 * WSDL stubs for:  http://dblp.l3s.de/WS/dblp++.php?wsdl
 *   Generated by:  matthias
 *           Date:  Fri May  7 14:39:59 2010
 *        Emitter:  Objective-C
 */

#import "DBLP.h"

/*-
 *   Method Name:  venue_title
 * Documentation:  <no documentation>
 */
@implementation venue_title
- (void) setParameters:(NSString*) in_dblp_key
{
    id _paramValues[] = {    
        in_dblp_key,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"titleString"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"venue_title"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#venue_title"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* venue_title */


/*-
 *   Method Name:  publication_data2
 * Documentation:  <no documentation>
 */
@implementation publication_data2
- (void) setParameters:(NSString*) in_dblp_key
{
    id _paramValues[] = {    
        in_dblp_key,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    //return [[super getResultDictionary] objectForKey: @"resultArray"];
    return [[[super getResultDictionary] objectForKey:@"/Result"] objectForKey:@"return"]; 
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"publication_data2"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#publication_data2"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* publication_data2 */


/*-
 *   Method Name:  all_publications_keywords_year
 * Documentation:  <no documentation>
 */
@implementation all_publications_keywords_year
- (void) setParameters:(NSString*) in_searchTerm in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear in_limit:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_limit
{
    id _paramValues[] = {    
        in_searchTerm,        
        in_startYear,        
        in_endYear,        
        in_limit,        
    };    
    NSString* _paramNames[] = {    
        @"searchTerm",        
        @"startYear",        
        @"endYear",        
        @"limit",        
    };    
    [super setParameters:4 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    //return [[super getResultDictionary] objectForKey: @"resultArray"];
	//return [super getResultDictionary];
    return [[[super getResultDictionary] objectForKey:@"/Result"] objectForKey:@"return"]; 
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"all_publications_keywords_year"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_publications_keywords_year"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* all_publications_keywords_year */


/*-
 *   Method Name:  all_publications_venue_year
 * Documentation:  <no documentation>
 */
@implementation all_publications_venue_year
- (void) setParameters:(NSString*) in_dblp_key_frag in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear
{
    id _paramValues[] = {    
        in_dblp_key_frag,        
        in_startYear,        
        in_endYear,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key_frag",        
        @"startYear",        
        @"endYear",        
    };    
    [super setParameters:3 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"resultArray"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"all_publications_venue_year"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_publications_venue_year"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* all_publications_venue_year */


/*-
 *   Method Name:  all_journal_titles
 * Documentation:  <no documentation>
 */
@implementation all_journal_titles
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"resultArray"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"all_journal_titles"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_journal_titles"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* all_journal_titles */


/*-
 *   Method Name:  publication_bibtex
 * Documentation:  <no documentation>
 */
@implementation publication_bibtex
- (void) setParameters:(NSString*) in_dblp_key
{
    id _paramValues[] = {    
        in_dblp_key,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"resultArray"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"publication_bibtex"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#publication_bibtex"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* publication_bibtex */


/*-
 *   Method Name:  all_journal_titles_year
 * Documentation:  <no documentation>
 */
@implementation all_journal_titles_year
- (void) setParameters:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_year
{
    id _paramValues[] = {    
        in_year,        
    };    
    NSString* _paramNames[] = {    
        @"year",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"titleString"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"all_journal_titles_year"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_journal_titles_year"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* all_journal_titles_year */


/*-
 *   Method Name:  publication_data
 * Documentation:  <no documentation>
 */
@implementation publication_data
- (void) setParameters:(NSString*) in_dblp_key
{
    id _paramValues[] = {    
        in_dblp_key,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"resultArray"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"publication_data"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#publication_data"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* publication_data */


/*-
 *   Method Name:  all_proceeding_titles
 * Documentation:  <no documentation>
 */
@implementation all_proceeding_titles
- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"resultArray"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"all_proceeding_titles"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_proceeding_titles"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* all_proceeding_titles */


/*-
 *   Method Name:  all_publications_author_year
 * Documentation:  <no documentation>
 */
@implementation all_publications_author_year
- (void) setParameters:(NSString*) in_firstName in_familyName:(NSString*) in_familyName in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear
{
    id _paramValues[] = {    
        in_firstName,        
        in_familyName,        
        in_startYear,        
        in_endYear,        
    };    
    NSString* _paramNames[] = {    
        @"firstName",        
        @"familyName",        
        @"startYear",        
        @"endYear",        
    };    
    [super setParameters:4 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"resultArray"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"all_publications_author_year"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#all_publications_author_year"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* all_publications_author_year */


/*-
 *   Method Name:  publication_authors
 * Documentation:  <no documentation>
 */
@implementation publication_authors
- (void) setParameters:(NSString*) in_dblp_key
{
    id _paramValues[] = {    
        in_dblp_key,        
    };    
    NSString* _paramNames[] = {    
        @"dblp_key",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    //return [[super getResultDictionary] objectForKey: @"resultArray"];
    return [[[super getResultDictionary] objectForKey:@"/Result"] objectForKey:@"return"];
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dblp.l3s.de/WS/dblp++.php"            
                 methodName: @"publication_authors"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:soapservice#Service#publication_authors"            
            methodNamespace: @"urn:soapservice"            
        ];        
}

@end; /* publication_authors */



@implementation DBLPPlusPlusService

+ (id) all_publications_author_year:(NSString*) in_firstName in_familyName:(NSString*) in_familyName in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear
{
    id result = NULL;    
    all_publications_author_year* _invocation = [[all_publications_author_year alloc] init];    
    [_invocation setParameters: in_firstName in_familyName:in_familyName in_startYear:in_startYear in_endYear:in_endYear];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) publication_data2:(NSString*) in_dblp_key
{
    id result = NULL;    
    publication_data2* _invocation = [[publication_data2 alloc] init];    
    [_invocation setParameters: in_dblp_key];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) publication_authors:(NSString*) in_dblp_key
{
    id result = NULL;    
    publication_authors* _invocation = [[publication_authors alloc] init];    
    [_invocation setParameters: in_dblp_key];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) all_publications_venue_year:(NSString*) in_dblp_key_frag in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear
{
    id result = NULL;    
    all_publications_venue_year* _invocation = [[all_publications_venue_year alloc] init];    
    [_invocation setParameters: in_dblp_key_frag in_startYear:in_startYear in_endYear:in_endYear];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) all_journal_titles
{
    id result = NULL;    
    all_journal_titles* _invocation = [[all_journal_titles alloc] init];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) publication_bibtex:(NSString*) in_dblp_key
{
    id result = NULL;    
    publication_bibtex* _invocation = [[publication_bibtex alloc] init];    
    [_invocation setParameters: in_dblp_key];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) all_publications_keywords_year:(NSString*) in_searchTerm in_startYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_startYear in_endYear:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_endYear in_limit:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_limit
{
    id result = NULL;    
    all_publications_keywords_year* _invocation = [[all_publications_keywords_year alloc] init];    
    [_invocation setParameters: in_searchTerm in_startYear:in_startYear in_endYear:in_endYear in_limit:in_limit];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) venue_title:(NSString*) in_dblp_key
{
    id result = NULL;    
    venue_title* _invocation = [[venue_title alloc] init];    
    [_invocation setParameters: in_dblp_key];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) all_journal_titles_year:(CFTypeRef /* Complex type http://www.w3.org/2001/XMLSchema|integer */) in_year
{
    id result = NULL;    
    all_journal_titles_year* _invocation = [[all_journal_titles_year alloc] init];    
    [_invocation setParameters: in_year];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) publication_data:(NSString*) in_dblp_key
{
    id result = NULL;    
    publication_data* _invocation = [[publication_data alloc] init];    
    [_invocation setParameters: in_dblp_key];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) all_proceeding_titles
{
    id result = NULL;    
    all_proceeding_titles* _invocation = [[all_proceeding_titles alloc] init];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}



@end;


/*-
 * End of WSDL document at http://dblp.l3s.de/WS/dblp++.php?wsdl
 */
